import { PlayerDTO } from "./types";

const colors = [
  "#FF0000",
  "#00FF00",
  "#0000FF",
  "#FFFF00",
  "#FF00FF",
  "#00FFFF",
  "#FF00FF",
  "#00FF7F",
  "#00BFFF",
  "#FFA500",
  "#800080",
  "#40E0D0",
  "#FFD700",
  "#FF7F50",
  "#FF8C69",
  "#8A2BE2",
  "#F5F5DC",
  "#808000",
  "#800000",
  "#008080",
];

export function randomDarkColor() {
  const index = Math.floor(Math.random() * colors.length);
  return colors[index];
}

export function getPlayerHead(player: PlayerDTO) {
  return player.body[0];
}

export function getPlayerRadiusFromScore(score: number) {
  const A = 1;
  const B = 10;
  return Math.sqrt((score * A) / Math.PI) + B;
}

export function getOrbSizeFromPoints(score: number) {
  const A = 0.5;
  const B = 0.5;
  return Math.sqrt((score * A) / Math.PI) + B;
}

const userNameList = [
"Polished Granite",
"Polished Diorite",
"Polished Andesite",
"Wooden Plank (Oak)",
"Wooden Plank (Spruce)",
"Wooden Plank (Birch)",
"Wooden Plank (Jungle)",
"Wooden Plank (Acacia)",
"Wooden Plank (Dark Oak)",
"Sapling (Spruce)",
"Sapling (Birch)",
"Sapling (Jungle)",
"Sapling (Acacia)",
"Sapling (Dark Oak)",
"Water (No Spread)",
"Lava (No Spread)",
"Leaves (Spruce)",
"Leaves (Birch)",
"Leaves (Jungle)",
"Lapis Lazuli Ore",
"Lapis Lazuli Block",
"Sandstone (Chiseled)",
"Sandstone (Smooth)",
"Rail (Powered)",
"Rail (Detector)",
"Sticky Piston",
"Tall Grass (Dead Shrub)",
"Tall Grass (Fern)",
"Light Blue Wool",
"Light Gray Wool",
"Piston (Moving)",
"Brown Mushroom",
"Stone Slab (Double)",
"Sandstone Slab (Double)",
"Wooden Slab (Double)",
"Cobblestone Slab (Double)",
"Brick Slab (Double)",
"Stone Brick Slab (Double)",
"Nether Brick Slab (Double)",
"Quartz Slab (Double)",
"Smooth Stone Slab (Double)",
"Smooth Sandstone Slab (Double)",
"Sandstone Slab",
"Cobblestone Slab",
"Stone Brick Slab",
"Nether Brick Slab",
"Wooden Stairs (Oak)",
"Redstone Wire",
"Block of Diamond",
"Furnace (Smelting)",
"Wood Door (Block)",
"Cobblestone Stairs",
"Sign (Wall Block)",
"Stone Pressure Plate",
"Iron Door (Block)",
"Wooden Pressure Plate",
"Redstone Ore (Glowing)",
"Redstone Torch (Off)",
"Redstone Torch",
"Button (Stone)",
"Sugar Cane (Block)",
"Jack-O-Lantern",
"Redstone Repeater (Block Off)",
"Redstone Repeater (Block On)",
"Stained Glass (White)",
"Stained Glass (Orange)",
"Stained Glass (Magenta)",
"Stained Glass (Light Blue)",
"Stained Glass (Yellow)",
"Stained Glass (Lime)",
"Stained Glass (Pink)",
"Stained Glass (Gray)",
"Stained Glass (Light Grey)",
"Stained Glass (Cyan)",
"Stained Glass (Purple)",
"Stained Glass (Blue)",
"Stained Glass (Brown)",
"Stained Glass (Green)",
"Stained Glass (Red)",
"Stained Glass (Black)",
"Monster Egg (Stone)",
"Monster Egg (Cobblestone)",
"Monster Egg (Stone Brick)",
"Monster Egg (Mossy Stone Brick)",
"Monster Egg (Cracked Stone)",
"Monster Egg (Chiseled Stone)",
"Mossy Stone Bricks",
"Cracked Stone Bricks",
"Chiseled Stone Brick",
"Brown Mushroom (Block)",
"Red Mushroom (Block)",
"Fence Gate (Oak)",
"Stone Brick Stairs",
"Nether Brick Fence",
"Nether Brick Stairs",
"Enchantment Table",
"Brewing Stand (Block)",
"Cauldron (Block)",
"End Portal Frame",
"Redstone Lamp",
"Redstone Lamp (On)",
"Oak-Wood Slab (Double)",
"Spruce-Wood Slab (Double)",
"Birch-Wood Slab (Double)",
"Jungle-Wood Slab (Double)",
"Acacia Wood Slab (Double)",
"Dark Oak Wood Slab (Double)",
"Oak-Wood Slab",
"Spruce-Wood Slab",
"Birch-Wood Slab",
"Jungle-Wood Slab",
"Acacia Wood Slab",
"Dark Oak Wood Slab",
"Sandstone Stairs",
"Tripwire Hook",
"Block of Emerald",
"Wooden Stairs (Spruce)",
"Wooden Stairs (Birch)",
"Wooden Stairs (Jungle)",
"Command Block",
"Cobblestone Wall",
"Mossy Cobblestone Wall",
"Flower Pot (Block)",
"Potatoes (Crop)",
"Head Block (Skeleton)",
"Head Block (Wither)",
"Head Block (Zombie)",
"Head Block (Steve)",
"Head Block (Creeper)",
"Anvil (Slightly Damaged)",
"Anvil (Very Damaged)",
"Trapped Chest",
"Weighted Pressure Plate (Light)",
"Weighted Pressure Plate (Heavy)",
"Redstone Comparator (Off)",
"Redstone Comparator (On)",
"Daylight Sensor",
"Block of Redstone",
"Nether Quartz Ore",
"Chiseled Quartz Block",
"Pillar Quartz Block",
"Quartz Stairs",
"Rail (Activator)",
"Stained Clay (White)",
"Stained Clay (Orange)",
"Stained Clay (Magenta)",
"Stained Clay (Light Blue)",
"Stained Clay (Yellow)",
"Stained Clay (Lime)",
"Stained Clay (Pink)",
"Stained Clay (Gray)",
"Stained Clay (Light Gray)",
"Stained Clay (Cyan)",
"Stained Clay (Purple)",
"Stained Clay (Blue)",
"Stained Clay (Brown)",
"Stained Clay (Green)",
"Stained Clay (Red)",
"Stained Clay (Black)",
"Stained Glass Pane (White)",
"Stained Glass Pane (Orange)",
"Stained Glass Pane (Magenta)",
"Stained Glass Pane (Light Blue)",
"Stained Glass Pane (Yellow)",
"Stained Glass Pane (Lime)",
"Stained Glass Pane (Pink)",
"Stained Glass Pane (Gray)",
"Stained Glass Pane (Light Gray)",
"Stained Glass Pane (Cyan)",
"Stained Glass Pane (Purple)",
"Stained Glass Pane (Blue)",
"Stained Glass Pane (Brown)",
"Stained Glass Pane (Green)",
"Stained Glass Pane (Red)",
"Stained Glass Pane (Black)",
"Leaves (Acacia)",
"Leaves (Dark Oak)",
"Wood (Acacia Oak)",
"Wood (Dark Oak)",
"Wooden Stairs (Acacia)",
"Wooden Stairs (Dark Oak)",
"Iron Trapdoor",
"Prismarine Bricks",
"Dark Prismarine",
"Carpet (White)",
"Carpet (Orange)",
"Carpet (Magenta)",
"Carpet (Light Blue)",
"Carpet (Yellow)",
"Carpet (Light Gray)",
"Carpet (Purple)",
"Carpet (Brown)",
"Carpet (Green)",
"Carpet (Black)",
"Hardened Clay",
"Double Tallgrass",
"Standing Banner (Block)",
"Wall Banner (Block)",
"Inverted Daylight Sensor",
"Red Sandstone",
"Red Sandstone (Chiseled)",
"Red Sandstone (Smooth)",
"Red Sandstone Stairs",
"Red Sandstone Slab (Double)",
"Red Sandstone Slab",
"Fence Gate (Spruce)",
"Fence Gate (Birch)",
"Fence Gate (Jungle)",
"Fence Gate (Dark Oak)",
"Fence Gate (Acacia)",
"Fence (Spruce)",
"Fence (Jungle)",
"Fence (Dark Oak)",
"Fence (Acacia)",
"Wooden Door Block (Spruce)",
"Wooden Door Block (Birch)",
"Wooden Door Block (Jungle)",
"Wooden Door Block (Acacia)",
"Wooden Door Block (Dark Oak)",
"Chorus Flower",
"Purpur Pillar",
"Purpur Stairs",
"Purpur Slab (Double)",
"End Stone Bricks",
"Nether Wart (Block)",
"Nether Brick (Red)",
"Shulker Box (Purple)",
"Structure Block",
"Flint and Steel",
"Wooden Shovel",
"Wooden Pickaxe",
"Stone Pickaxe",
"Diamond Sword",
"Diamond Shovel",
"Diamond Pickaxe",
"Mushroom Stew",
"Leather Helmet",
"Leather Chestplate",
"Leather Leggings",
"Leather Boots",
"Chainmail Helmet",
"Chainmail Chestplate",
"Chainmail Leggings",
"Chainmail Boots",
"Iron Chestplate",
"Iron Leggings",
"Diamond Helmet",
"Diamond Chestplate",
"Diamond Leggings",
"Diamond Boots",
"Gold Chestplate",
"Gold Leggings",
"Cooked Porkchop",
"Enchanted Golden Apple",
"Bucket (Water)",
"Redstone Dust",
"Minecart (Storage)",
"Minecart (Powered)",
"Glowstone Dust",
"Cooked Salmon",
"Cactus Green Dye",
"Light Gray Dye",
"Dandelion Yellow Dye",
"Light Blue Dye",
"Redstone Repeater",
"Pumpkin Seeds",
"Cooked Chicken",
"Nether Wart Seeds",
"Awkward Potion",
"Mundane Potion",
"Regeneration Potion (0:45)",
"Swiftness Potion (3:00)",
"Fire Resistance Potion (3:00)",
"Poison Potion (0:45)",
"Healing Potion",
"Night Vision Potion (3:00)",
"Weakness Potion (1:30)",
"Strength Potion (3:00)",
"Slowness Potion (1:30)",
"Harming Potion",
"Water Breathing Potion (3:00)",
"Invisibility Potion (3:00)",
"Regeneration Potion II (0:22)",
"Swiftness Potion II (1:30)",
"Poison Potion II (0:22)",
"Healing Potion II",
"Strength Potion II (1:30)",
"Leaping Potion II (1:30)",
"Harming Potion II",
"Regeneration Potion (2:00)",
"Swiftness Potion (8:00)",
"Fire Resistance Potion (8:00)",
"Poison Potion (2:00)",
"Night Vision Potion (8:00)",
"Weakness Potion (4:00)",
"Strength Potion (8:00)",
"Slowness Potion (4:00)",
"Leaping Potion (3:00)",
"Water Breathing Potion (8:00)",
"Invisibility Potion (8:00)",
"Regeneration Potion II (1:00)",
"Swiftness Potion II (4:00)",
"Poison Potion II (1:00)",
"Strength Potion II (4:00)",
"Regeneration Splash (0:33)",
"Swiftness Splash (2:15)",
"Fire Resistance Splash (2:15)",
"Poison Splash (0:33)",
"Healing Splash",
"Night Vision Splash (2:15)",
"Weakness Splash (1:07)",
"Strength Splash (2:15)",
"Slowness Splash (1:07)",
"Harming Splash",
"Breathing Splash (2:15)",
"Invisibility Splash (2:15)",
"Regeneration Splash II (0:16)",
"Swiftness Splash II (1:07)",
"Poison Splash II (0:16)",
"Healing Splash II",
"Strength Splash II (1:07)",
"Leaping Splash II (1:07)",
"Harming Splash II",
"Regeneration Splash (1:30)",
"Swiftness Splash (6:00)",
"Fire Resistance Splash (6:00)",
"Poison Splash (1:30)",
"Night Vision Splash (6:00)",
"Weakness Splash (3:00)",
"Strength Splash (6:00)",
"Slowness Splash (3:00)",
"Leaping Splash (2:15)",
"Breathing Splash (6:00)",
"Invisibility Splash (6:00)",
"Regeneration Splash II (0:45)",
"Swiftness Splash II (3:00)",
"Poison Splash II (0:45)",
"Strength Splash II (3:00)",
"Fermented Spider Eye",
"Brewing Stand",
"Glistering Melon (Slice)",
"Spawn Egg (Creeper)",
"Spawn Egg (Skeleton)",
"Spawn Egg (Spider)",
"Spawn Egg (Zombie)",
"Spawn Egg (Slime)",
"Spawn Egg (Ghast)",
"Spawn Egg (Zombie Pigmen)",
"Spawn Egg (Endermen)",
"Spawn Egg (Cave Spider)",
"Spawn Egg (Silverfish)",
"Spawn Egg (Blaze)",
"Spawn Egg (Magma Cube)",
"Spawn Egg (Bat)",
"Spawn Egg (Witch)",
"Spawn Egg (Endermite)",
"Spawn Egg (Guardian)",
"Spawn Egg (Shulker)",
"Spawn Egg (Pig)",
"Spawn Egg (Sheep)",
"Spawn Egg (Cow)",
"Spawn Egg (Chicken)",
"Spawn Egg (Squid)",
"Spawn Egg (Wolf)",
"Spawn Egg (Mooshroom)",
"Spawn Egg (Ocelot)",
"Spawn Egg (Horse)",
"Spawn Egg (Rabbit)",
"Spawn Egg (Polar Bear)",
"Spawn Egg (Villager)",
"Bottle of Enchanting",
"Book and Quill",
"Poisonous Potato",
"Golden Carrot",
"Head (Skeleton)",
"Head (Creeper)",
"Carrot on a Stick",
"Firework Rocket",
"Firework Star",
"Enchanted Book",
"Redstone Comparator",
"Nether Brick (Item)",
"Nether Quartz",
"Minecart (TNT)",
"Minecart (Hopper)",
"Prismarine Shard",
"Prismarine Crystals",
"Cooked Rabbit",
"Iron Horse Armor",
"Gold Horse Armor",
"Diamond Horse Armor",
"Minecart (Command Block)",
"Cooked Mutton",
"Banner (Black)",
"Banner (Green)",
"Banner (Brown)",
"Banner (Purple)",
"Banner (Light Gray)",
"Banner (Yellow)",
"Banner (Light Blue)",
"Banner (Magenta)",
"Banner (Orange)",
"Banner (White)",
"Wooden Door (Spruce)",
"Wooden Door (Birch)",
"Wooden Door (Jungle)",
"Wooden Door (Acacia)",
"Wooden Door (Dark Oak)",
"Chorus Fruit (Popped)",
"Beetroot Seeds",
"Beetroot Soup",
"Dragon's Breath",
"Arrow (Spectral)",
"Totem of Undying",
"Shulker Shell",
"Music Disk (13)",
"Music Disk (Cat)",
"Music Disk (Blocks)",
"Music Disk (Chirp)",
"Music Disk (Far)",
"Music Disk (Mall)",
"Music Disk (Mellohi)",
"Music Disk (Stal)",
"Music Disk (Strad)",
"Music Disk (Ward)",
"Music Disk (11)",
"Music Disk (Wait)",
]
export function getRandomUsername() {
  const index = Math.floor(Math.random() * userNameList.length);
  return userNameList[index];
}