import { PlayerDTO } from './types.js';

export const colors = [
  '#FF0000',
  '#00FF00',
  '#0000FF',
  '#FFFF00',
  '#FF00FF',
  '#00FFFF',
  '#FF00FF',
  '#00FF7F',
  '#00BFFF',
  '#FFA500',
  '#800080',
  '#40E0D0',
  '#FFD700',
  '#FF7F50',
  '#FF8C69',
  '#8A2BE2',
  '#F5F5DC',
  '#808000',
  '#800000',
  '#008080',
];

export function randomDarkColor() {
  return Math.floor(Math.random() * colors.length);
}

export function getPlayerHead(player: PlayerDTO) {
  return player.body[0];
}

export function getPlayerRadiusFromScore(score: number) {
  const A = 1;
  const B = 10;
  return Math.sqrt((score * A) / Math.PI) + B;
}

export function getOrbSizeFromPoints(score: number) {
  const A = 0.5;
  const B = 0.5;
  return Math.sqrt((score * A) / Math.PI) + B;
}

const userNameList = [
  'Polished Granite',
  'Polished Diorite',
  'Polished Andesite',
  'Wooden Plank',
  'Sapling',
  'Water',
  'Lava',
  'Leaves',
  'Lapis Lazuli Ore',
  'Lapis Lazuli Block',
  'Sandstone',
  'Rail',
  'Sticky Piston',
  'Tall Grass',
  'Light Blue Wool',
  'Light Gray Wool',
  'Piston',
  'Brown Mushroom',
  'Stone Slab',
  'Sandstone Slab',
  'Wooden Slab',
  'Cobblestone Slab',
  'Brick Slab',
  'Stone Brick Slab',
  'Nether Brick Slab',
  'Quartz Slab',
  'Smooth Stone Slab',
  'Smooth Sandstone Slab',
  'Wooden Stairs',
  'Redstone Wire',
  'Block of Diamond',
  'Furnace',
  'Wood Door',
  'Cobblestone Stairs',
  'Sign',
  'Stone Pressure Plate',
  'Iron Door',
  'Wooden Pressure Plate',
  'Redstone Ore',
  'Redstone Torch',
  'Button',
  'Sugar Cane',
  'Jack-O-Lantern',
  'Redstone Repeater',
  'Stained Glass',
  'Monster Egg',
  'Mossy Stone Bricks',
  'Cracked Stone Bricks',
  'Chiseled Stone Brick',
  'Red Mushroom',
  'Fence Gate',
  'Stone Brick Stairs',
  'Nether Brick Fence',
  'Nether Brick Stairs',
  'Enchantment Table',
  'Brewing Stand',
  'Cauldron',
  'End Portal Frame',
  'Redstone Lamp',
  'Oak-Wood Slab',
  'Spruce-Wood Slab',
  'Birch-Wood Slab',
  'Jungle-Wood Slab',
  'Acacia Wood Slab',
  'Dark Oak Wood Slab',
  'Sandstone Stairs',
  'Tripwire Hook',
  'Block of Emerald',
  'Command Block',
  'Cobblestone Wall',
  'Mossy Cobblestone Wall',
  'Flower Pot',
  'Potatoes',
  'Head Block',
  'Anvil',
  'Trapped Chest',
  'Weighted Pressure Plate',
  'Redstone Comparator',
  'Daylight Sensor',
  'Block of Redstone',
  'Nether Quartz Ore',
  'Chiseled Quartz Block',
  'Pillar Quartz Block',
  'Quartz Stairs',
  'Stained Clay',
  'Stained Glass Pane',
  'Wood',
  'Iron Trapdoor',
  'Prismarine Bricks',
  'Dark Prismarine',
  'Carpet',
  'Hardened Clay',
  'Double Tallgrass',
  'Standing Banner',
  'Wall Banner',
  'Inverted Daylight Sensor',
  'Red Sandstone',
  'Red Sandstone Stairs',
  'Red Sandstone Slab',
  'Fence',
  'Wooden Door Block',
  'Chorus Flower',
  'Purpur Pillar',
  'Purpur Stairs',
  'Purpur Slab',
  'End Stone Bricks',
  'Nether Wart',
  'Nether Brick',
  'Shulker Box',
  'Structure Block',
  'Flint and Steel',
  'Wooden Shovel',
  'Wooden Pickaxe',
  'Stone Pickaxe',
  'Diamond Sword',
  'Diamond Shovel',
  'Diamond Pickaxe',
  'Mushroom Stew',
  'Leather Helmet',
  'Leather Chestplate',
  'Leather Leggings',
  'Leather Boots',
  'Chainmail Helmet',
  'Chainmail Chestplate',
  'Chainmail Leggings',
  'Chainmail Boots',
  'Iron Chestplate',
  'Iron Leggings',
  'Diamond Helmet',
  'Diamond Chestplate',
  'Diamond Leggings',
  'Diamond Boots',
  'Gold Chestplate',
  'Gold Leggings',
  'Cooked Porkchop',
  'Enchanted Golden Apple',
  'Bucket',
  'Redstone Dust',
  'Minecart',
  'Glowstone Dust',
  'Cooked Salmon',
  'Cactus Green Dye',
  'Light Gray Dye',
  'Dandelion Yellow Dye',
  'Light Blue Dye',
  'Pumpkin Seeds',
  'Cooked Chicken',
  'Nether Wart Seeds',
  'Awkward Potion',
  'Mundane Potion',
  'Regeneration Potion',
  'Swiftness Potion',
  'Fire Resistance Potion',
  'Poison Potion',
  'Healing Potion',
  'Night Vision Potion',
  'Weakness Potion',
  'Strength Potion',
  'Slowness Potion',
  'Harming Potion',
  'Water Breathing Potion',
  'Invisibility Potion',
  'Regeneration Potion II',
  'Swiftness Potion II',
  'Poison Potion II',
  'Healing Potion II',
  'Strength Potion II',
  'Leaping Potion II',
  'Harming Potion II',
  'Leaping Potion',
  'Regeneration Splash',
  'Swiftness Splash',
  'Fire Resistance Splash',
  'Poison Splash',
  'Healing Splash',
  'Night Vision Splash',
  'Weakness Splash',
  'Strength Splash',
  'Slowness Splash',
  'Harming Splash',
  'Breathing Splash',
  'Invisibility Splash',
  'Regeneration Splash II',
  'Swiftness Splash II',
  'Poison Splash II',
  'Healing Splash II',
  'Strength Splash II',
  'Leaping Splash II',
  'Harming Splash II',
  'Leaping Splash',
  'Fermented Spider Eye',
  'Glistering Melon',
  'Spawn Egg',
  'Bottle of Enchanting',
  'Book and Quill',
  'Poisonous Potato',
  'Golden Carrot',
  'Head',
  'Carrot on a Stick',
  'Firework Rocket',
  'Firework Star',
  'Enchanted Book',
  'Nether Quartz',
  'Prismarine Shard',
  'Prismarine Crystals',
  'Cooked Rabbit',
  'Iron Horse Armor',
  'Gold Horse Armor',
  'Diamond Horse Armor',
  'Cooked Mutton',
  'Banner',
  'Wooden Door',
  'Chorus Fruit',
  'Beetroot Seeds',
  'Beetroot Soup',
  "Dragon's Breath",
  'Arrow',
  'Totem of Undying',
  'Shulker Shell',
  'Music Disk',
];
export function getRandomUsername() {
  const index = Math.floor(Math.random() * userNameList.length);
  return userNameList[index];
}
